chapterBackgrounds[0] = "GUICHP0A"
chapterBackgrounds[1] = "GUICHP1A"
chapterBackgrounds[2] = "GUICHP2A"
chapterBackgrounds[3] = "GUICHP3A"
chapterBackgrounds[4] = "GUICHP4A"
chapterBackgrounds[5] = "GUICHP5A"
chapterBackgrounds[6] = "GUICHP6A"
chapterBackgrounds[7] = "GUICHP7A"
chapterBackgrounds[8] = "GUICHP1B"
chapterBackgrounds[9] = "GUICHP2B"
chapterBackgrounds[10] = "GUICHP3B"
chapterBackgrounds[11] = "GUICHP4B"
chapterBackgrounds[12] = "GUICHP5B"
chapterBackgrounds[13] = "GUICHP6B"

chapterBackgrounds[20] = "BPEND"

chapterBackgrounds[52] = "GUIDRM2"
chapterBackgrounds[53] = "GUIDRM3"
chapterBackgrounds[54] = "GUIDRM4"
chapterBackgrounds[55] = "GUIDRM5"
chapterBackgrounds[56] = "GUIDRM6"
chapterBackgrounds[57] = "GUIDRM7"
chapterBackgrounds[58] = "ARRIVEA"
chapterBackgrounds[59] = "LEAVEA"

chapterBackgrounds[100] = "GUICHP6B"
